name: Tournamental
version: 0.6
main: me.Chryb.Tournamental.Tournamental
author: Chryb
website: http://rested.de
commands:
   defzone:
      description: This is a defregion command.
      permission: <plugin name>.defzone
      usage: /<command> [zone-name]
   tlist:
      description: This is a plugininfo command.
      permission: <plugin name>.plugininfo
      usage: /<command>
   addclass:
      description: This is a addclass command.
      permission: <plugin name>.addclass
      usage: /<command> [player] [class]
   addlobby:
      description: This is a addlobby (for arena) command.
      permission: <plugin name>.addlobby
      usage: /<command> [zone-name]
   addfight:
      description: This is a addfight (for arena) command.
      permission: <plugin name>.addfight
      usage: /<command> [zone-name]
   addteam:
      description: This is a addteam (for arena) command.
      permission: <plugin name>.addteam
      usage: /<command> [zone-name]
   getlevel:
      description: This is a getlevel (for admins) command.
      permission: <plugin name>.getlevel
      usage: /<command> [level]